/* Data type definitions for the video streaming example */

module cctypes {
    // limits on element sizes
    const uint32 MAX_SEQUENCE_LEN = 18800000;       // 18.8MB == 100K MPEG-TS 188-byte packets
    const uint8 KEY_STRING_LEN = 8;

    // this is the bulk datatype for sending streaming video/audio data
    struct ccBulk {
        @key
        string<KEY_STRING_LEN> pub_id;              // ID string of the publisher
        sequence<octet, MAX_SEQUENCE_LEN> data;     // payload of data
    };
};