/*********************************************************************************************
(c) 2005-2013 Copyright, Real-Time Innovations, Inc.  All rights reserved.    	                             
RTI grants Licensee a license to use, modify, compile, and create derivative works 
of the Software.  Licensee has the right to distribute object form only for use with RTI 
products.  The Software is provided “as is”, with no warranty of any type, including 
any warranty for fitness for any purpose. RTI is under no obligation to maintain or 
support the Software.  RTI shall not be liable for any incidental or consequential 
damages arising out of the use or inability to use the software.
**********************************************************************************************/

module com {
module rti {
module media {
module generated {

const string VIDEO_TOPIC = "VideoData";

const string QOS_LIBRARY = "RTIExampleQosLibrary";
const string QOS_PROFILE_STREAMING_DATA = "StreamingVideoData";
const string QOS_PROFILE_MULTICAST_DATA = "MulticastVideo";


// 1024 * 1024 is the maximum frame size
// Data will be allocated at this size, but
// only the actual size of the frame will 
// be sent.
const long MAX_BUFFER_SIZE = 1048576;

struct VideoStream {

	// This allows a subscriber to differentiate between different video
	// publishers that are publishing the same data on the same Topic.
	long stream_id;  //@key

	// Some video formats may require metadata to be sent with the binary
	// video data, such as flags or a frame sequence_number.
	unsigned long flags;
	unsigned long sequence_number;

	// This contains the video buffers
	sequence <octet, MAX_BUFFER_SIZE> frame; 
};

}; // generated
}; // video
}; // rti
}; // com 
